### ISSUE TITLE
jCarousel ignores last item on specific markup

### ISSUE THREAD

**Issue by Binternet** [jsor/jcarousel#735]
For some unknown reason, jCarousel ignores the last item when I output markup [ http://pastebin.com/5LKUypr6 ] through WordPress [counts 7 items instead of 8] yet when I do a static loop to output 10 items, it counts them correctly [ http://pastebin.com/VJhjBz4S ] couldn't find a reasonable reason for that yet I did reproduce it over and over again.

**Comment by jsor** [comment]
Hard to say without seeing the complete setup. Do have this online where i can see it?

**Comment by Binternet** [comment]
Yep, http://212.150.22.55/~esekphone

It's in hebrew so don't break your teeth ;-)

jCarousel appears with the pagination numbers on the top-left. you can see it counts 7 yet I have 8 <li> elements.

**Comment by jsor** [comment]
That was kinda tricky :). The reason is, that your 7th item has a width of 270px, while the other items and the clip element have a width of 271px. So, jCarousel considered the 8th element as part of page 7 since 1 pixel is visible. See also issue #617.

It should be fixed now. Can you try the [updated](https://github.com/jsor/jcarousel/blob/master/dist/jquery.jcarousel.min.js) file?

**Comment by Binternet** [comment]
Updated the file, works like a charm!

**Comment by jsor** [comment]
Great. Thanks for reporting this issue!
