### ISSUE TITLE
JCarousel sometimes is offcentered

### ISSUE THREAD

**Issue by andrewyang96** [jsor/jcarousel#756]
When I deployed a [website](http://sss.ae.illinois.edu) with a jCarousel plugin, I found that jCarousel sometimes glitched. The jCarousel seemed to initialize before the images were loaded and I would start with half an image and an incorrect number of slide buttons. Here's a screenshot:

![jCarousel glitch](http://i.imgur.com/cEPfIuj.png)

Can anyone figure this out? Thanks!

**Comment by jsor** [comment]
The problem is, that you don't set a width for your carousel items. jCarousel can only calculate correctly once all images loaded. You can try to [reload](http://sorgalla.com/jcarousel/docs/reference/api.html#reload) the carousel on window.load or (use something [imagesloaded](http://imagesloaded.desandro.com)).
