### ISSUE TITLE
Documentation doesn't mention lack of styling. And no css file is present except in the examples

### ISSUE THREAD

**Issue by bigomega** [jsor/jcarousel#763]

**Comment by jsor** [comment]
The [docs](http://sorgalla.com/jcarousel/docs/reference/installation.html#style-the-carousel) mention the minimum CSS required for jCarousel. 0.2 had some default "skins", maybe it's a good idea to add them also for 0.3.

And since we're on Github here, feel free to send pull requests with improvements ;)
