### ISSUE TITLE
'circular' option not working

### ISSUE THREAD

**Issue by alexandernst** [jsor/jcarousel#798]
Demo http://codepen.io/alexandernst/pen/ZWrmMm

Hitting the "right" button 3 times will move the carousel to the left. But then, the next 2 clicks won't move anything. Then 1 more click will "restart" the carousel.

**Comment by jsor** [comment]
The problem is, that you don't set a explicit width for your carousel items. jCarousel can only calculate correctly once all images loaded. You can try to [reload](http://sorgalla.com/jcarousel/docs/reference/api.html#reload) the carousel on window.load or (use something like [imagesloaded](http://imagesloaded.desandro.com)).
